<?php


?>


<br><br>
<form action="addComponent" method="post">
    <div id="controllerDiv">
        <label for="controller">Controller : </label>
        <input type="text" name="controller" id="controller">
    </div>
<!-- 
    for more robust code I can use to add multiple action inputs to be add as per need. 
    Same as I've used it MongoDB task to add meta data and Variant 
-->
    <div id="actionsDiv">
        <label for="action">Actions : </label>
        <input type="text" name="action" id="action">
    </div>

    <button type="submit">Add Component</button>
</form>